In [1]:
from util.middleman import MiddleMan
import numpy as np

In [2]:
mm = MiddleMan()
mm.add_supplier('D1', 20, 10)
mm.add_supplier('D2', 30, 12)

mm.add_receiver('O1', 10, 30)
mm.add_receiver('O2', 28, 25)
mm.add_receiver('O3', 27, 30)

transport_cost_matrix = np.array([
    [8, 14, 17],
    [12, 9, 19]
])

mm.add_transport_matrix(transport_cost_matrix)

mm.calculate()

array([[ 12,   1,   3, -10],
       [  6,   4,  -1, -12],
       [ 30,  25,  30,   0]])

In [7]:
mm.calculate_overall_return()

262.0

In [9]:
mm.unit_profits


array([[12,  1,  3,  0],
       [ 6,  4, -1,  0],
       [ 0,  0,  0,  0]])

In [10]:

mm.sales

array([[10.,  0., 10.,  0.],
       [ 0., 28.,  0.,  2.],
       [ 0.,  0., 17., 48.]])

In [4]:
mm.calculate_returns()

array([[120.,   0.,  30.],
       [  0., 112.,  -0.]])